### ISSUE TITLE
The Method QuerydslKeyValueRepository.findOne(Predicate predicate) throws exception when Spring boot  application is run from command line [DATAKV-237]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-keyvalue#214]
**[Valerii Sukhotskyi](https://jira.spring.io/secure/ViewProfile.jspa?name=suhoff)** opened **[DATAKV-237](https://jira.spring.io/browse/DATAKV-237?redirect=false)** and commented

I have created simple Spring Boot + Spring Data Key-Value + Querydsl application (https://github.com/suhotskiy/spring-data-keyvalue-querydsl-bug).
When I run: **_mvn spring-boot:run_** all works fine. But when the application is run from the command line: **_java -jar example-0.0.1-SNAPSHOT.jar_** the exception is raised:

```java
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: com.mysema.codegen.CodegenException: Compilation of public class Q_133914572_1275614662_1275614662_1195259493 {

    public static Iterable<com.suhoff.example.City> eval(Iterable<com.suhoff.example.City> city_, String a1) {
java.util.List<com.suhoff.example.City> rv = new java.util.ArrayList<com.suhoff.example.City>();
for (com.suhoff.example.City city : city_) {
    try {
        if (com.querydsl.collections.CollQueryFunctions.equals(city.getCountry(), a1)) {
            rv.add(city);
        }
    } catch (NullPointerException npe) { }
}
return rv;    }

}

 failed.
/Q_133914572_1275614662_1275614662_1195259493.java:3: error: package com.suhoff.example does not exist
    public static Iterable<com.suhoff.example.City> eval(Iterable<com.suhoff.example.City> city_, String a1) {
                                                                                    ^
/Q_133914572_1275614662_1275614662_1195259493.java:3: error: package com.suhoff.example does not exist
    public static Iterable<com.suhoff.example.City> eval(Iterable<com.suhoff.example.City> city_, String a1) {
                                             ^
/Q_133914572_1275614662_1275614662_1195259493.java:4: error: package com.suhoff.example does not exist
java.util.List<com.suhoff.example.City> rv = new java.util.ArrayList<com.suhoff.example.City>();
                                 ^
/Q_133914572_1275614662_1275614662_1195259493.java:4: error: package com.suhoff.example does not exist
java.util.List<com.suhoff.example.City> rv = new java.util.ArrayList<com.suhoff.example.City>();
                                                                                       ^
/Q_133914572_1275614662_1275614662_1195259493.java:5: error: package com.suhoff.example does not exist
for (com.suhoff.example.City city : city_) {
                       ^
/Q_133914572_1275614662_1275614662_1195259493.java:7: error: package com.querydsl.collections does not exist
        if (com.querydsl.collections.CollQueryFunctions.equals(city.getCountry(), a1)) {
                                    ^
6 errors

        at com.mysema.codegen.JDKEvaluatorFactory.compile(JDKEvaluatorFactory.java:74)
        at com.mysema.codegen.AbstractEvaluatorFactory.createEvaluator(AbstractEvaluatorFactory.java:128)
        at com.querydsl.collections.DefaultEvaluatorFactory.createEvaluator(DefaultEvaluatorFactory.java:151)
        at com.querydsl.collections.DefaultQueryEngine.evaluateSingleSource(DefaultQueryEngine.java:166)
        at com.querydsl.collections.DefaultQueryEngine.list(DefaultQueryEngine.java:80)
        at com.querydsl.collections.AbstractCollQuery.iterate(AbstractCollQuery.java:175)
        at com.querydsl.collections.AbstractCollQuery.fetchOne(AbstractCollQuery.java:204)
        at org.springframework.data.keyvalue.repository.support.QuerydslKeyValueRepository.findOne(QuerydslKeyValueRepository.java:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:359)
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:644)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:608)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy40.findOne(Unknown Source)
        at com.suhoff.example.ExampleApplication.main(ExampleApplication.java:22)
        ... 8 more
}
```

---

**Affects:** 2.1.2 (Lovelace SR2)

**Reference URL:** https://github.com/suhotskiy/spring-data-keyvalue-querydsl-bug

**Comment by jxblum** [comment]
This seems to have been a Java agent / byte code manipulation problem.

Additionally, this Issue was reported on now, out-of-date Spring Boot and Spring Data versions.

Not certain what the current state of this relationship (Spring + [Codegen](https://mvnrepository.com/artifact/com.mysema.codegen)) would be so closing this ticket.
