### ISSUE TITLE
Get an error in the GeneratingIdAccessor`s constructor when the @Id is nor specified

### ISSUE THREAD

**Issue by Mikhail2048** [spring-projects/spring-data-keyvalue#466]
When I create an entity, let's say `Order` without `@Id` property, like this:

```
@Data
@KeySpace("orders")
@NoArgsConstructor
@AllArgsConstructor
public class Order {

    public Integer id;
    public OffsetDateTime createdAt;
    public OffsetDateTime expiredAt;
    public boolean isActive;
}
```

Then, in `KeyValueTempalte#insert()` I get an error during instantiation of the `GeneratingIdAccessor`, we pass null as identifier, so we get an assertion error. I think getting as assertion error in the constructor of the internal framework class is inherently wrong and it should be treated as a bug. We must get the error not when we invoke `KeyValueRepostiory#save()` method, but during the application startup.

**Comment by mp911de** [comment]
Can you please provide a full stack trace?

**Comment by Mikhail2048** [comment]
Of course, here it is:

```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:785) ~[spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:772) ~[spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.2.jar:2.5.2]
	at org.example.App.main(App.java:24) ~[classes/:na]
Caused by: java.lang.IllegalArgumentException: Identifier property must not be null!
	at org.springframework.util.Assert.notNull(Assert.java:201) ~[spring-core-5.3.8.jar:5.3.8]
	at org.springframework.data.keyvalue.core.GeneratingIdAccessor.<init>(GeneratingIdAccessor.java:49) ~[spring-data-keyvalue-2.5.2.jar:2.5.2]
	at org.springframework.data.keyvalue.core.KeyValueTemplate.insert(KeyValueTemplate.java:154) ~[spring-data-keyvalue-2.5.2.jar:2.5.2]
	at org.springframework.data.keyvalue.repository.support.SimpleKeyValueRepository.save(SimpleKeyValueRepository.java:77) ~[spring-data-keyvalue-2.5.2.jar:2.5.2]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:289) ~[spring-data-commons-2.5.2.jar:2.5.2]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.5.2.jar:2.5.2]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.5.2.jar:2.5.2]
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:529) ~[spring-data-commons-2.5.2.jar:2.5.2]
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285) ~[spring-data-commons-2.5.2.jar:2.5.2]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:599) ~[spring-data-commons-2.5.2.jar:2.5.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar:5.3.8]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:163) ~[spring-data-commons-2.5.2.jar:2.5.2]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138) ~[spring-data-commons-2.5.2.jar:2.5.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar:5.3.8]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.8.jar:5.3.8]
	at jdk.proxy2/jdk.proxy2.$Proxy55.save(Unknown Source) ~[na:na]
	at org.example.App.run(App.java:29) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782) ~[spring-boot-2.5.2.jar:2.5.2]
```

```
@EnableScheduling
@SpringBootApplication
@EnableMapRepositories
public class App implements ApplicationRunner {

    @Autowired
    private OrdersCache ordersCache;

    public static void main( String[] args ) {
        SpringApplication.run(App.class, args);
    }

    @Override
    public void run(ApplicationArguments args) {
        ordersCache.save(new Order(123, now(), now(), true)); // We get exception here

        Order order = ordersCache.findById(123).orElse(null);

        System.out.println("order = " + order);
    }
}
```
The problem is that we get an error when we trigger `save` method. It is wired, because the entity without `@Id` in the spring-data-keyvalue does not make sense and we should not get this error on runtime. Better will be to get this error on startup time.

**Comment by mp911de** [comment]
Thanks a lot. `KeyValueTemplate.save(…)` requires an identifier property to be able to store the object. The ID value is required for keyspace events and for the `KeyValueAdapter.put(…)` method.
